numeric:
- V258
- C1
- C13
- card1
- card2
- TransactionAmt
- addr1
- C14
- D2
- V294
- D1
- D15
- D4
- V257
- C2
- V242
- card5
- C11
- C8
- D10
- V317
- dist1
- C6
- V149
- C7
- card3
- V70
- V295
- D8
- C4
- D3
- id_02
- C10
- C9
- id_20
- V313
- C5
- V62
- V45
- V308
- V315
- D11
- V30
- V310
- V318
- V87
- V201
- id_19
- V53
- V281
categorical:
- DeviceInfo
- R_emaildomain
- id_31
- P_emaildomain
- card6
- id_33
- id_30
- M5
- M4
- M6
